### ISSUE TITLE
API Error - Missing Scope

### ISSUE THREAD

**Issue by mentallabyrinth** [kasunkv/slack-notification#16]
Hello,

Thank for making this extension, however, it's not working for us. We're not sure why and if it's a fault of ours. We followed the instructions and generated a token using the "Legacy Token Generator." When the task runs on Azure Dev Ops,  it fails and we get the following message: 

`"An API error occurred: missing_scope"`

While creating the legacy token, there's no option to modify scopes. According to the generator the following scopes are enabled by default: `identify`, `read `, `post`, `client`, and `admin`. Are we doing something wrong?

The version we're using is: 5.* (According to the Azure Dev Ops Task display)

Thank you.

**Comment by justinokay** [comment]
I'm having this same issue. I tried legacy token and received that error. I also tried app level token and set the scrope to read and write to which I get this error:

Task Failed. Error: "One or more messages failed to deliver. An API error occurred: invalid_auth"
##[error]Task Failed. Error: "One or more messages failed to deliver. An API error occurred: invalid_auth"

**Comment by opslm** [comment]
Same here. Curl works with this token without problems. 
```
  - task: SlackNotification@6
    inputs:
      SlackApiToken: '$(slack_token)'
      MessageAuthor: 'Azure DevOps'
      Channel: 'devops-az-devops'
      NotificationType: 'ChatMessage'
      Message: 'Tost'
```

![image](https://user-images.githubusercontent.com/131865162/235114296-801ffbce-e31c-4ef2-a9ac-b6fc47a6c694.png)
 
![image](https://user-images.githubusercontent.com/131865162/235115163-80e60130-52db-4d51-a3a2-f0782255113a.png)

**Comment by olegbzk** [comment]
Same here. Curl works with this token without problems. 
```
  - task: SlackNotification@6
    inputs:
      SlackApiToken: '$(slack_token)'
      MessageAuthor: 'Azure DevOps'
      Channel: 'devops-az-devops'
      NotificationType: 'ChatMessage'
      Message: 'Tost'
```

![image](https://user-images.githubusercontent.com/131865162/235114296-801ffbce-e31c-4ef2-a9ac-b6fc47a6c694.png)
 
![image](https://user-images.githubusercontent.com/131865162/235115163-80e60130-52db-4d51-a3a2-f0782255113a.png)
